### ISSUE TITLE
Create a test command

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#10]
As a developer, I want a single command that I can run which runs the same tests that travis runs so that I can be confident my branch will pass before I push to travis.

Currently, travis runs these commands separately:

```
 - pep8 calaccess_raw
 - pyflakes calaccess_raw
 - python example/manage.py createcalaccessrawmodeldocs
 - pushd docs && make html && popd
 - coverage run example/manage.py test calaccess_raw
```

**Comment by adborden** [comment]
And stick it in the README so folks know how to use it :)

**Comment by adborden** [comment]
Looks like tox might do this for us, I opened this issue https://github.com/california-civic-data-coalition/django-calaccess-raw-data/issues/275 to clarify.

**Comment by adborden** [comment]
This exists now, should be added to the README

```
$ make test
```

**Comment by bcipolli** [comment]
This command exists, and is in the `README.md`. We do need to add the additional checks into the `Makefile`, however.

**Comment by bcipolli** [comment]
Should be fixed in https://github.com/caciviclab/disclosure-backend/commit/0ab79ad3c61f59d97219a8117e0d2de91aee3389

**Comment by adborden** [comment]
:+1:
