### ISSUE TITLE
Add top-level "fips_id" and "name" to GET /locations/{fips_id} endpoint

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend#107]
Currently the API response for this endpoint contains:

``` json
{
  "location": {
    "next_election": "2015-11-04",
    "name": "San Francisco",
    "fip_id": "1234"
  }
}
```

@jnmarcus suggests that various Angular libraries will work better if the structure has top-level keys with names like:

``` json
{
  "fips_id": "1234",
  "name": "San Francisco"
}
```

The fate of the "location" key is unknown, but I see no reason to maintain both it _and_ the top-level keys.

**Comment by bcipolli** [comment]
We didn't use `FIPS`, but we added a `/locality/{locality_id}` endpoint, as well as a `/locality/search` endpoint. I believe that addresses this issue.
