### ISSUE TITLE
Implement a management command to transform data from netfile schema to our own internal schema

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#110]
#103 designs the schema; #109 implements a schema. This issue is for implementing a management command that takes raw netfile data (either from csv files, or from the database) and creates the appropriate models in our internal schema.

Again, glad for anybody to take this on. Haven't heard a peep, and this is crucial to getting basic APIs up for the front-end. So I will assign this to myself and see if I can get something working relatively quickly. Even if not totally correct, it will help:
- Front-end folks move forward to have live API endpoints.
- Non-technical people start entering data.

**Comment by bcipolli** [comment]
For anybody interested in playing with the data who doesn't know SQL but does know Python, try this branch: 
https://github.com/bcipolli/opendisclosure-backend/tree/xform-netfile

Run:

```
python manage.py xformnetfiledata --agencies SJC --years 2015
```

This will break into the debugger and give you command-line access to the raw data as a pandas data frame. You can run:
- `data.keys()` to see all available columns
- `data['key_name'].unique()` to see all unique values in the column, and get a flavor for what's in there.

@andrell81 @mikeubell not sure if this might be useful to either of you.

**Comment by bcipolli** [comment]
My plan for prototyping this:
1. Read the raw csv using pandas.
2. Filter rows based on form (start with Form 460 or 497 data).
3. Get/create all location IDs. (iterate over unique names, use Django's `get_or_create`)
4. Get/create all candidate/ballot_measure_choice Ids (along with ballot/ballot_measure for 'unknown', if no ballot data has been entered for the candidate / ballot measure)
5. Get/create all Committee / contributor IDs, using `get_or_create`.
6. Insert a row into `contributions` table, referring to models from 2-5.

This won't be strictly correct to start, but it will be enough to move on to getting live APIs up & running.

**Comment by adborden** [comment]
Yep, filtering based on form sounds like a great place to start. I'm not familiar with pandas, how does it help us in these steps? Sounds like pandas is more about analysis, but from what I understand about this ticket, this is mostly about mapping netfile fields to our models.

I think there are a number of challenges in these steps, so I was originally thinking we would have several management commands to breakdown the discrete steps you mention (something I've been referring to as the data pipeline or the ETL pipeline. High-level questions:

> 1. Get/create all location IDs. (iterate over unique names, use Django's get_or_create)

What fields are you using uniquely identify Location? I don't think there's FIPS in the netfile data. I think the only thing you have to go is based on city/state? And if that's the case, are we including zipcode as part of this?

> 1. Get/create all candidate/ballot_measure_choice Ids (along with ballot/ballot_measure for 'unknown', if no ballot data has been entered for the candidate / ballot measure)

I don't think there's any ballot data in the netfile data. All you have is the filerId, which corresponds to a committee (I think), but AFAIK, there's no link from committee to a ballot measure or candidate. In practice, we've deduced the ballot measure or candidate relationship to the committee based on the committee name (similarly to deduce support/opposed stance).

Side note, the schedule D form does refer to a stance, but it might not completely cover all committees since it's based on expenditures. Potentially there's nothing stopping one from filing expenditures that support a measure AND expenditures that oppose a measure. No one has dug into this yet.

> 1. Get/create all Committee / contributor IDs, using get_or_create.

Just curious what you're using for the contributor ID here and what you have in mind. Do you see de-duping as part of this command in the pipeline? I assume for the committee, you'll be using the Filer ID?

I might break out the contributor pass into it's own command because _I think_ this involves using names and addresses to identify a single contributor, maybe some manual work (and one-off rules), and creating our own ID since netfile doesn't assign contributor IDs. We've been calling this problem with contributors the "de-dupe" problem and AFAIK, haven't spent much time working on it besides throwing around the name of the [dedupe](https://github.com/datamade/dedupe) library as if it were the holy grail ;)

Or were you thinking _contribution_ Id?

**Comment by bcipolli** [comment]
@aborden Thanks for the thoughts. My plan was to do a rapid prototype in a single management command, separating code by function. Refactoring into management commands shouldn't be hard, but doing all in one would make things easier to develop in the short-term.

Thanks for the notes on each item, it's very helpful! I will address each one as I go, so will update along the way. Lemme know if you have any concerns with that!

**Comment by adborden** [comment]
*clarification, the [data key](https://data.sfgov.org/City-Management-and-Ethics/Campaign-Finance-Data-Key/wygs-cc76) does claim that schedule A would have `bal_num` and `sup_opp_cd` and other office fields, which could be used to connect a contribution to a ballot measure and stance or candidate office. And while these fields do exist in the netfile data, they are not populated for form 460A.

**Comment by adborden** [comment]
@bcipolli yeah, that strategy sound fine.

**Comment by bcipolli** [comment]
@adborden re: Pandas, it's the main Python library for doing data analysis from CSV files. They have a lot of functions for selecting columns, filtering rows, visualizing data, and the like. It's based on the R language "DataFrame" object.

It's good stuff! http://pandas.pydata.org/

**Comment by adborden** [comment]
So even though we have the data loaded into the DB, you plan on using pandas and the CSVs directly?

Is there a point to loading the netfile data into the DB as is using the existing calacces (the loading command that exists today)?

**Comment by bcipolli** [comment]
Depends on how complicated the joins across the tables are. Pandas is definitely easier to work with than Django, if the JOINs are simple. Since Netfile has one main table (and two total), Pandas seemed like the way to go. And from where I come from, Pandas is a major library, very familiar, and a great tool for people to learn for filtering CSV data.

If the Netfile API can't be parsed with Pandas, then it's likely hard to use for others, so I figured it could also be a way to push back on Netfile people to make their APIs better. Most people I know use R/Pandas.

The code on the Django side for loading data isn't my favorite, either--there's quite a bit happening in raw SQL. I like keeping  a managed layer (pandas or django) between the raw data (CSV/SQL) and the code; I find it to generally come out cleaner.

**Comment by bcipolli** [comment]
I filtered column definitions from https://data.sfgov.org/City-Management-and-Ethics/Campaign-Finance-Data-Key/wygs-cc76 (referenced in https://github.com/caciviclab/disclosure-backend/issues/60) with the netfile data obtained via the `downloadnetfilerawdata` management command, and I get:

```
agency_shortcut: 
amountType     : 
amt_Incur      : Amount incurred this period
amt_Paid       : Amount paid this period
bakRef_TID     : Back Reference to a Tran_ID of a "parent" record
bal_Juris      : nan
bal_Name       : nan
bal_Num        : nan
beg_Bal        : Outstanding balance at beginning of this period
calculated_Amount: 
calculated_Date: 
cand_NamF      : nan
cand_NamL      : nan
cand_NamS      : nan
cand_NamT      : nan
cmte_Id        : Committee ID # (If [COM|RCP] & no ID#, Treas info Req.)
dist_No        : nan
elec_Date      : Date of Election (Required if Late Contribution Made)
end_Bal        : Outstanding blanace at close of this period
entity_Cd      : Contributor Type of Entity (Individual, Political Party, Small Contributor Committee, Other - e.g. a Bus, Cmtte, Org,...)
externalId     : 
filerId        : 
filerName      : 
filingId       : 
form_Type      : Schedule from Form 460
g_From_E_F     : Back reference from schedule G to E or F
int_CmteId     : Committee ID for Transfer or Intermediary (required when Tran_type = X)
int_Rate       : 
intr_Adr1      : Intermediary Address Line 1
intr_Adr2      : Intermediary Address Line 2
intr_City      : Intermediary City
intr_Emp       : Intermediary Employer
intr_NamF      : Intermediary First Name
intr_NamL      : Intermediary Last Name
intr_NamS      : Intermediary Suffix
intr_NamT      : Intermediary Title or Prefix
intr_Occ       : Intermediary Occupation
intr_ST        : Intermediary State
intr_Self      : Intermediary Self Employed? (check box value)
intr_Zip4      : Intermediary Zip
juris_Cd       : nan
juris_Dscr     : nan
latitude       : 
lender_Name    : 
loan_Amt1      : Loan Amount (Amount Received this Period)
loan_Amt2      : Outstanding Balance
loan_Amt3      : Cumulative Cont. to Date (Calendar Year)
loan_Amt4      : Outstanding Balance Beginning this Period
loan_Amt5      : Amount Paid this Period (B1 only)
loan_Amt6      : Amount Forgiven this Period (B1 only)
loan_Amt7      : Amount of Interest Paid this Period (B1 only)
loan_Amt8      : Original Amount of Loan (B1 only)
loan_Date1     : Date Loan Incurred (Original Date)
loan_Date2     : Date Due (Date Loan Due)
loan_Rate      : Interest Rate on a Loan
longitude      : 
memo_Code      : Memo Amount (Date/Amount are informational only)
memo_RefNo     : Reference to text contained in a TEXT record
netFileKey     : 
off_S_H_Cd     : nan
office_Cd      : Office Sought
office_Dscr    : 
rec_Type       : Record Type Value (Type of data, IE: Cover Page, Expenditure, etc.)
sup_Opp_Cd     : nan
tran_Adr1      : Transaction Entity's Address Line 1
tran_Adr2      : Transaction Entity's Address Line 2
tran_Amt1      : Transaction Amount
tran_Amt2      : Cumulative Year-To-Date
tran_ChkNo     : 
tran_City      : Transaction Entity's City
tran_Code      : 
tran_Date      : Transaction Date
tran_Date1     : Transaction Date (if a range)
tran_Dscr      : Transaction Description
tran_Emp       : Transaction Entity's Employer
tran_Id        : Transaction ID # (not necessarily consistent between Original and Amendments)
tran_NamF      : Transaction Entity's First Name
tran_NamL      : Transaction Entity's Last Name or Business Name
tran_NamS      : Transaction Entity's Suffix
tran_NamT      : Transaction Entity's Prefix or Title
tran_Occ       : Transaction Entity's Occupation
tran_ST        : 
tran_Self      : Transaction Entity's self employed status (check box)
tran_Type      : Transaction Type (T=Third Party Repayment, F=Forgiven Loan, R=Returned (Neg. Amt?), I=Intermediary, X=Transfer)
tran_Zip4      : Transaction Entity's Zip Code
transactionType: 
tres_Adr1      : Treasurer Address Line 1 (Req if [COM|RCP] & no ID#)
tres_Adr2      : Treasurer Address Line 2
tres_City      : Treasurer City
tres_NamF      : Treasurer First Name (Req if [COM|RCP] & no ID#)
tres_NamL      : Treasurer Last Name (Req if [COM|RCP] & no ID#)
tres_NamS      : Treasurer Suffix
tres_NamT      : Treasurer Title or Prefix
tres_ST        : Treasurer State
tres_Zip4      : Treasurer Zip
xref_Match     : Related item on another schedule has same transaction ID
xref_SchNum    : 
```

**Comment by bcipolli** [comment]
At our brigade meeting last night, @mrmaximize offered to help make this happen. Please read this thread to get the latest info and find the reference to a branch where we're exploring these things!

**Comment by bcipolli** [comment]
At our brigade meeting last night, @mrmaksimize offered to help make this happen. Please read this thread to get the latest info and find the reference to a branch where we're exploring these things!

**Comment by MrMaksimize** [comment]
Got some changes going here:
https://github.com/MrMaksimize/disclosure-backend/tree/xform-netfile 

@bcipolli updated your branch with current master and moved the command to the disclosure_backend directory.  Unless there's a reason you wanted it separate.  

More updates as I go along :)

**Comment by bcipolli** [comment]
Cool! The directory thing was due to downstream directory name changes that I was working off of; no sweat.

**Comment by bcipolli** [comment]
The basic command is complete. We should open new issues to address individual shortcomings.
