### ISSUE TITLE
Election and Race data

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#13]
We don't have a source for "what exists on my ballot". Let's start with Race and Election models.

Right now this involves going to the Agency's website, looking up the election data, and manually entering them in the django admin interface (for a model that currently doesn't exist).

This data should be exported as a fixture and committed to git. The fixture should be loaded on db initialization so folks setting up a dev instance will have a working site.

**Comment by seanius** [comment]
The "Race" will have name, which will be the name of the office, or the name of the ballot measure.

**Comment by adborden** [comment]
Consider basing our models off of http://votinginfoproject.github.io/vip-specification/

**Comment by adborden** [comment]
I implemented some models based on VIP in #47 That should be good to get us off the ground (no doubt will need tweaking as we go).

BTW, rather than "race" I thought the work "contest" was more appropriate and that we should adopt that going forward.
