### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#132]
https://github.com/blog/1184-contributing-guidelines

I would like to see this include:
- A bit about setting up a test environment
- A bit about where to find specs & technical docs (including the glossary).

Writing code:
- A bit about overall app structure, and how to keep apps relatively light-weight
- A bit about docstrings and `help_text`
- A bit about test coverage
- A bit about code formats (pep8, flake8)

Code reviews:
- A bit about running tests locally
- A bit about what good PRs look like.
- A bit about our process & expectations

That's all that comes to mind at the moment.. glad for others to add (or reject haha)

**Comment by adborden** [comment]
Sounds good. I've been meaning to finalize [this PR](https://github.com/caciviclab/caciviclab.github.io/pull/5) for an orgwide Code of Conduct... but I'd like all project CONTRIBUTING to include a link to the org's CONTRIBUTING.

**Comment by bcipolli** [comment]
Duplicate of #33
