### ISSUE TITLE
BallotItemResponse should be BallotItemDescription

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/disclosure-backend#133]
The BallotITemResponse model contains the title, text and arguments for and against a measure.  Also the comment says: YES/NO to a referendum, or a candidate.  Which does not describe it at all.

**Comment by bcipolli** [comment]
Hey @mikeubell , thanks for the feedback! Each entry in that table represents a possible response to a `BallotItem`.  For binary referendums, we'll have one `BallotItemResponse` for "YES", one for "NO". For office elections, we'll have one `BallotItemResponse` per candidate. 

It looks like the `BallotItem` doesn't have a `description`/`text` field to describe the `BallotItem` beyond the name. Would adding a `BallotItem.description` field be useful?

If not, if you can point me to an example of a `BallotItem` that we could use for reference, to discuss getting a better schema set up, that'd be great. Thanks!

**Comment by mikeubell** [comment]
I don't understand this.  What do you mean an Response for "YES" and one for "NO"?  Is this for getting election results?  Where/how?

BallotItemResponse has fields: title, brief, full_text, {pro,con}_statement, ballot_item.  How can this be a "response"?  This describes (or really defines) the ballot item.  There is no fields for describing candidates.

**Comment by bcipolli** [comment]
@mikeubell Has this been resolved to your satisfaction?

**Comment by mikeubell** [comment]
👍
