### ISSUE TITLE
Annotations for committees

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#14]
We don't have data for "What is this Committee's stance on a particular issue?". We'll add that manually through the django admin interface. We'll need an `AnnotatedCommittee` model.

This data should be exported as a fixture and imported on db initialization so that dev instances have a working site.

**Comment by seanius** [comment]
The stance of a committee can be "for" or "against" in the case of a ballot measure, and in the case of an office, it will be the name of the candidate that they support.

**Comment by bcipolli** [comment]
@adborden Are  you thinking of anything beyond properties of the `committee` and `ballot_measure_response`? If not, do we need a separate model?

Right now, this is a property on the committee directly. It's only one property, and every committee has to have a value, so this seemed easiest.

Glad to understand what you have in mind better.

**Comment by bcipolli** [comment]
Given the current setup, I don't believe we need a new object; it's already in `Beneficiary`. Manual annotations are recorded in `LogEntry` objects.

The manual work remains.

**Comment by bcipolli** [comment]
I think we have this in our schema, and this can be input currently in the admin database. Incidentally, this data is somewhat available in the Form 496 data, and I will try to pull some from there, when available.
