### ISSUE TITLE
civic.json per spec

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#148]
https://github.com/BetaNYC/civic.json/blob/master/specification.md
- `needs` should be an array of `need` objects.
- `categories` should be an array of `category` objects.

**Comment by adborden** [comment]
I had to ping @ondrae because something seemed a little fishy about the the example civic.json files I saw in other projects. Turns out CFAPI has it's own spec: https://github.com/codeforamerica/brigade/blob/master/README-Project-Search.md#civicjson

**Comment by adborden** [comment]
I should read before I type... :expressionless: 

Looks like the CFAPI stuff is limited in what it supports, only two fields. Let's conform the civic.json to BetaNYC's spec, and add the `tags` field as per CFA. Assuming it doesn't break anything, we can support both.
