### ISSUE TITLE
Pull out dependency on our own calaccess_raw fork.

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#15]
We've made a handful of changes to calaccess_raw which should go upstream. We don't need to have a forked version, none of our changes are unique to our app. Keeping disclosure on their app reduces complexity of merging in upstream fixes and features.

Before getting rid of the calaccess_raw fork, we need to integrate this change upstream to avoid running out of memory on small aws instances.
1. Shard the loading of the CSV into database (1649883, 49e4cfa1e8).

There's also this one, but not required for our code, just a nice fix.
1. Postgres COPY superuser issue (6ac6bfb19)

**Comment by bcipolli** [comment]
Note that I've submitted the memory change as an upstream PR (https://github.com/california-civic-data-coalition/django-calaccess-raw-data/pull/1151). Once that's accepted, should be good to go here.

**Comment by tdooner** [comment]
This is done, even if we have a forked version of the dependency. (They just merged my memory fix upstream, so we should be able to un-fork `calacces_raw`!)

**Comment by bcipolli** [comment]
I updated the title to reflect the issue. This is done; `requirements.txt` references the vanilla version of `calaccess_raw`.
