### ISSUE TITLE
Rename CorporateBenefactor to OtherBenefactor model

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#153]
We currently assume that "other" benefactors are corporate benefactors. @andrell81 says this isn't appropriate.

We should rename `CorporateBenefactor` to `OtherBenefactor`. If we can verify some of the `OtherBenefactor`s, perhaps we can move them across tables... or slap on a property that labels them as verified corporate benefactors.

**Comment by mikeubell** [comment]
Looking at Oakland data to see what other than Corporations would be labeled OTH I see some PACs and individuals are labeled OTH.  These could be data errors. I have an email into Malid for possible clarification.

**Comment by bcipolli** [comment]
@andrell81 pointed out that "corporation" is rather specific; small business can appear in "other". But it's unclear what else...

**Comment by mikeubell** [comment]
I would think we might want to distinguish "commercial" benefactors vs. other benefactors that might fall into this category. Or do we want to distinguish LLC vs. S corporations vs. C Corporations.

**Comment by mikeubell** [comment]
ACtually its "CorporationBenefactor" in the code not "CorporateBenefactor"
