### ISSUE TITLE
Store cumulative total for the year on IndependentMoney

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#155]
@andrell81 suggests this could help associate individuals inside `xformrawnetfiledata`

**Comment by adborden** [comment]
A little more detail here? Cumulative total of `IndependentMoney` for a
single Beneficiary over a year?

On Wed, 2016-01-27 at 10:34 -0800, Ben Cipollini notifications@github.com wrote:

> @andrell81 suggests this could help associate individuals inside `xformrawnetfiledata`
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/caciviclab/disclosure-backend/issues/155

## 

Aaron Borden
Human and Hacker

**Comment by bcipolli** [comment]
@adborden Yes, exactly!

**Comment by bcipolli** [comment]
Fixed
