### ISSUE TITLE
Benefactor shows a "type" and "benefactor_type: that seem equivalent

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#158]
![image](https://cloud.githubusercontent.com/assets/4072455/12624723/56771a68-c4e5-11e5-95a0-3c948f6bb0bd.png)

If they are the same, one should be hidden and set to the other.

**Comment by bcipolli** [comment]
Also on corporatebenefactor: 
![image](https://cloud.githubusercontent.com/assets/4072455/12624932/519ae88e-c4e6-11e5-9958-91482f7f0798.png)

**Comment by mikeubell** [comment]
Am I right in thinking we do this via adding a ModelAdmin to exclude those fields?
+class CommitteeBenefactorAdmin(admin.ModelAdmin):
-    exclude = ('benefactor_type', 'benefactor_locality')
  +

**Comment by bcipolli** [comment]
@mikeubell That sounds about right, but I'm not 100% sure that will solve all the problems, or is the best way to address the issue. There are duplicate fields that need to stay in sync..
