### ISSUE TITLE
Errors Installing ( EnvironmentError: mysql_config not found)

### ISSUE THREAD

**Issue by amandabee** [caciviclab/disclosure-backend#18]
Trying to get this running, however I'm getting stuck on `EnvironmentError: mysql_config not found` -- @adborden  and I thought it might be for want of MySQL, but I installed MySQL server, and it is definitely running, but I'm still getting the following when I run `pip install -r requirements_dev.txt`:

```
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting Django (from -r requirements_dev.txt (line 1))
  Using cached Django-1.8.4-py2.py3-none-any.whl
Collecting mysqlclient (from -r requirements_dev.txt (line 2))
  Using cached mysqlclient-1.3.6.tar.gz
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-9HILNW/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 47, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-9HILNW/mysqlclient/setup.py", line 17, in <module>

        metadata, options = get_config()

      File "setup_posix.py", line 47, in get_config

        libs = mysql_config("libs_r")

      File "setup_posix.py", line 29, in mysql_config

        raise EnvironmentError("%s not found" % (mysql_config.path,))

    EnvironmentError: mysql_config not found

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9HILNW/mysqlclie
```

I'd love help figuring out what isn't working here. I'm on Ubuntu, not OSX, for whatever that happens to be worth.

**Comment by tdooner** [comment]
Hey @amandabee, you will need the package containing MySQL header files in order to build the mysql python module. You should be able to install it with:

```
sudo apt-get install libmysqlclient-dev
```

Then, try the `pip install` again and let me know how that goes.

**Comment by amandabee** [comment]
Awesome. I do see a warning:

>   Could not find a tag or branch 'dab635c6c242b11c81add0069c7d9ee1c842e866', assuming commit. 

But otherwise this works now. I think @erensi was having a similar problem on his Windows install. Not sure if the fix is the same.

**Comment by adborden** [comment]
The pip warning "could not find tag or branch...assuming commit" is just a warning and you can ignore it. It is indeed a commit in the case of the swagger module :)

## 

Aaron Borden
Human and Hacker
Sent from my mobile

On Aug 27, 2015 7:37 AM, Amanda Hickman notifications@github.com wrote:
Awesome. I do see a warning:

>   Could not find a tag or branch 'dab635c6c242b11c81add0069c7d9ee1c842e866', assuming commit.

But otherwise this works now. I think @erensi was having a similar problem on his Windows install. Not sure if the fix is the same.

---

**Comment by rkiddy** [comment]
I documented, as far as I could, the install procedure. See:

https://docs.google.com/document/d/1rQfHDM_wdOX2W38U44Iuv9341UmcIJgocqUICXR6soA/edit

You can also find it by going to the OpenCalifornia > ODCA folder and looking for:

'CCDC Applications for the "django-uninitiated"'

I am also using Ubuntu (14.04). It is sometimes a bit challenging to get Mac OS X instructions to work.... :-)

**Comment by amandabee** [comment]
Awesome. Seems like some of that belongs in a pull request to https://github.com/opencalifornia/disclosure-backend/blob/master/README.md, no? I'm not a Django _expert_ but I wouldn't have assumed that I needed to read _CCDC Applications for the "django-uninitiated"_ to install the `disclosure-backend` -- I've got a few other Django apps running. The issue was that I'm not using MySQL with any of them so I didn't have  `libmysqlclient-dev`

**Comment by seanius** [comment]
Ideally one shouldn't need anything not documented in the .md file, so
yeah, I would say "patches welcome" :)

**Comment by tdooner** [comment]
Just to clarify: do _not_ follow the "CCDC applications for the django uninitiated." It is a good guide, but not for people trying to set up the caciviclab/disclosure-backend project.

To set up this project, the only document you should need is the README.md. If there is something missing, please make sure you mention it in an issue or pull request so the next person that comes along will benefit from you hitting that roadblock.

**Comment by caiki** [comment]
Gracias tdooner , funciono!!!
