### ISSUE TITLE
Filter localities in admin panel

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#192]
Right now, all localities are loaded in all views. This is SLOW; there are tons, and we do a reverse string lookup to make them render meaningfully.

Better is to filter OUT zip-codes when displaying in the admin; they are never appropriate for our various locality filters (ballots, committees, etc).

**Comment by bcipolli** [comment]
@mikeubell I like what you've been doing with the admin panel. Could you try this one as well?

**Comment by mikeubell** [comment]
I wondered why it is so slow.  I'll take a look.

**Comment by bcipolli** [comment]
Perhaps `ZipCode` should not be included in `Locality`?

**Comment by bcipolli** [comment]
Same here: this is causing me problems tonight, haven't heard any updates, and it's a small fix--so should have a PR up shortly.
