### ISSUE TITLE
Entity resolution on people

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#195]
Should we combine people that match based on name, address, and `cumulative_money`? Or should we remain agnostic and create a new person for every `IND` row in Form 460 Schedule A?

Seems to me that we should combine... I don't see any downside. Either way (combine/not combine) is incorrect, but combining will be a more accurate estimate of the total # of individuals participating.

@andrell81 @ashajohn any thoughts? Assigning to @andrell81 ; we need someone responsible to work with others and make the final call on this.

![image](https://cloud.githubusercontent.com/assets/4072455/12958433/a9a37e5a-cfff-11e5-8651-cf4a1caf323e.png)

**Comment by mikeubell** [comment]
I think we should combine on name and address (I think we only have zip code).  Does a benefactor have a cumulative_money?  I am thinking it only applies to beneficiaries, my memory could be wrong.

**Comment by bcipolli** [comment]
> I think we should combine on name and address (I think we only have zip code)

I think we have address too... but this too will take entity resolution (i.e. there will be lots of mistakes & variations!)

> Does a benefactor have a cumulative_money?  I am thinking it only applies to beneficiaries, my memory could be wrong.

We have `cumulative_money` for benefactors (not beneficiaries), so yes, we can use that too. 

I agree that combining on all these factors (with some sludge-factor for errors in the data) is a good idea.

**Comment by mikeubell** [comment]
In the Oakland data we used name and zip and it  got many cases.

**Comment by bcipolli** [comment]
@mikeubell do you want to try this out? I think you've got the hang of this.

**Comment by bcipolli** [comment]
Haven't heard back on this, it's just one line of code, and it was useful to me tonight, so assigning to me. Will push a fix for this shortly.

**Comment by bcipolli** [comment]
This was fixed in #212
