### ISSUE TITLE
Styleguide page with example components

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#20]
https://slack-files.com/files-pri-safe/T02RZ6FDG-F09RQRKTN/odca-mobile-09-ballot_measure.pdf?c=1442465727-88c3ec42e390d1c34aaf4d9b35b247db880e650d

**Comment by adborden** [comment]
Probably a good idea to create a static styleguide html page, so you can see the UI elements with the live CSS.

**Comment by adborden** [comment]
@jnmarcus did a great job getting some the main components styled. I'm going to change this to being the style guide page.

**Comment by bcipolli** [comment]
The above link is broken, and I don't understand what this issue is about. @adborden could you update this please?

**Comment by tdooner** [comment]
I'm gonna close this because I think most UI elements seem more appropriate in the frontend project.
