### ISSUE TITLE
Understand negative Form 460A contributions

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#203]
I see these fly by... and they don't make sense. A quick query says they're about 0.6% of the data (282/45300 transactions in my local machine db).

What do they mean? What are we supposed to do with them?

**Comment by mikeubell** [comment]
I believe they are returned contributions. Just add the (negative) value to
the total contributions.

**Comment by bcipolli** [comment]
Let's close this for now. I will keep an eye on this moving forward.
