### ISSUE TITLE
Adding Candidates or OfficeElections via Admin fails

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/disclosure-backend#204]
![untitled](https://cloud.githubusercontent.com/assets/6759416/12994409/4349f694-d0d5-11e5-9cf2-e7cee2d4ed52.jpg)
![untitled](https://cloud.githubusercontent.com/assets/6759416/12994452/a8ceda16-d0d5-11e5-8c7f-04e78d237641.jpg)

**Comment by bcipolli** [comment]
This is due to assumptions in the constructors that backwards look-ups should work. They will not if all values are `None`. Simple fix is to check for `None` in the constructor, and if so do nothing.

**Comment by bcipolli** [comment]
This was fixed and merged.
