### ISSUE TITLE
Resolve questions / issues with Netfile feeds

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#207]
This is an issue to track outstanding questions from the Netfile folks. 

**Data feed questions:**
- Different endpoints on the same data have drastically different schemas (field names, as well as fields available, e.g. [ByYear](https://netfile.com/Connect2/api/swagger-ui/#!/public/ByYear) vs. [Query](https://netfile.com/Connect2/api/swagger-ui/#!/public/Query)). Can we resolve this?
- City names have very broad ranges of spelling; entity resolution must be done. Is this something planned by Netfile? If not, is there some way we can plug this in to the system directly?
- Some zip codes are not from this country. Is there a field to help detect this?

**Data issues / changes:**
- Transaction `d49d8441813c417984a3a332008e3015` has `entity_Cd=PTY`, but `tran_NamL=JPMorgan Chase & Co. PAC`. That must be an error.
- Agency name for SFO is weird (Contains `Ethics Commission` in the title). Can that be changed?
- Some zip codes are 00000?

**Comment by mikeubell** [comment]
The data is just what the filer entered.  As far as I know neither netfile nor the receiving agency do any validation.  I doubt there are really foreign zip codes. They are more likely just data errors.

**Comment by dmontgomery** [comment]
@mikeubell is correct.  The .CAL e-filing specification does not validate content for accuracy.  Things like zip codes and names are butchered all the time by filers.

The only possibility of correction would be for the receiving agency to require the filer to submit an amendment to the filing(s) in question.  The filer is required to respond to amendment requests, but I've never come across an agency willing to require an amendment to correct things like misspelled names...

**Comment by dmontgomery** [comment]
On a more general note, NetFile does not currently provide any data normalization services for e-filed content.

**Comment by bcipolli** [comment]
Thanks @dmontgomery ! Followed up via email on the endpoint schema differences; for the rest, we'll do our best to represent those data in reusable ways in our app!

**Comment by bcipolli** [comment]
We got answers for most things here. I've emailed @dmontgomery with questions for specific issues ( #49, #125). We can close this.
