### ISSUE TITLE
deploy additional branches of api to remote endpoints

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-backend#215]
this would help speed up frontend development significantly and will eventually be necessary once we are ready to "release" an official version of the site to the public.  Having at least something like "stable" and "unstable" on an initial basis, would be great.

I'm happy to help with this, but have no information on where the backend resides, and what that setup is like.  @tdooner @adborden would you have more information on this?

**Comment by bcipolli** [comment]
@jnmarcus right, great idea!

I think we can do this by having the "stable" (should be `master`) branch pushed to `admin.caciviclab.org`, and any unstable branch (an official one, say `develop`) is simply in the repo. Then you can simply check out the latest `develop` on your local machine, and point your front-end to that.

To set up a local version of the backend on your machine, just follow the instructions in this repo. If you get stuck, then our instructions aren't good enough and we should work together to update them.

How does that sound?

**Comment by jnmarcus** [comment]
@bcipolli as long as every time someone merges something into the unstable branch, it doesn't get pushed to the 'stable' branch, that works for me.  As far as where the stable branch is pushed to, as long as it's a remote, that's kool.  In general, from a usability standpoint,  I wonder if it makes sense to have things related to the api pushed to `api.caciviclab.org` so that we can differentiate from the admin interface location.  so potentially: `api.caciviclab.org/unstable/vX/` and `api.caciviclab.org/stable/vXX/`, but it's up to u guys.  As long as the frontend can

**Comment by bcipolli** [comment]
I created a `develop` branch, and made it the default--so new PRs will target `develop` by default.

We can merge `develop` to `master` when we see fit. This way, `master` can be used to deploy to the public server anytime.
