### ISSUE TITLE
Use ReportingPeriod to select / eliminate campaign finance information

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#222]
See https://github.com/caciviclab/caciviclab.github.io/wiki/Campaign-Finance for details.  Depends on `ReportingPeriod` data needed from #221.

**Comment by bcipolli** [comment]
Because we have the netfile xaction ID and a treasurer-reported ID, it's possible that we can simply skip reloading rows (rather than delete them), or modify/update them (in case $$ amount changed, or simply to report that the data were pulled from form 460A instead of 497, for example).

So, this could wind up being trivial.

**Comment by bcipolli** [comment]
This is actually non-trivial. Chatted with @andrell81 , have some good ideas on how to get this done.

**Comment by mikeubell** [comment]
We have gotten rid of the reporting period information so this is obsolete.
