### ISSUE TITLE
'type' property of the api endpoint: 'locality/search/' returns null

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-backend#238]
We need the `type` property in order to resolve the urls correctly from search.  Is it possible to have this added in sooner, rather than later?  Currently urls are resolving to `//{localeId}/{localeName}`, as a result.  (the `type` should go between the 2 backslashes at the beginning)

Also, just curious, why does it return the `type` at the endpoint: `/locality/{locality_id}` but not at `locality/search/`?

**Comment by bcipolli** [comment]
Hi @jnmarcus ; will take a look at this over the weekend!

**Comment by bcipolli** [comment]
It's due to the object type that's sent to the serializer.

Since we only have data on the city, we should only be returning results of cities. Getting this to work, however, is a really easy tweak. Will have this done tonight.

**Comment by bcipolli** [comment]
Turns out that, since we limit queries based only on localities we have ballot data for, this naturally returns only cities for our dataset :) 

![image](https://cloud.githubusercontent.com/assets/4072455/14947172/c2fc60fa-0fe3-11e6-88dc-93f9e1e02b1d.png)

**Comment by adborden** [comment]
I think this is fixed, seeing `type` being returned with a value.
