### ISSUE TITLE
Contribution & expenditure data prior to 2016 missing from calculations

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/disclosure-backend#279]
See campaigns for Jody London, Rebecca Kaplan, Lynette Gibson-McElhaney, and Roseann Torres

McElhaney & Kaplan did significant fundraising & spending in 2015.

I did not include 2017 statements in my calculations, so the totals may change when those are included as well. 

Spreadsheet attached.
[Summary totals 2016 election (updated thru 11.9.17).xlsx](https://github.com/caciviclab/disclosure-backend/files/1476359/Summary.totals.2016.election.updated.thru.11.9.17.xlsx)

**Comment by mikeubell** [comment]
There is corruption in the 2015 data.  Note that the record for MUTIU is missing fields but is ok in the PDF.
![filing](https://user-images.githubusercontent.com/6759416/33530583-706b18e6-d836-11e7-93c7-c2c373afd6b8.jpeg)
![mutiu](https://user-images.githubusercontent.com/6759416/33530584-70845a18-d836-11e7-84c9-e6c99c8f62a1.jpeg)

(Also this issue should be in backend-static not backend, wonder if there is way to move an issue?)

**Comment by mikeubell** [comment]
moved to backend-static
