### ISSUE TITLE
Need to exclude data for officeholder accounts from campaign totals

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/disclosure-backend#280]
Larry Reid and Lynette Gibson-McElhaney changed their campaign committees to Officeholder committees in the midst of a reporting period. 

Transactions after they filed the change should be excluded/subtracted from the campaign totals.

Larry Reid for Council 2016 Officeholder Committee	FPPC ID 1387905	re-designated	12/19/2016
Lynette Gibson-McElhaney 2016 Officeholder Committee FPPC ID 1375179 re-designated 8/29/2017

**Comment by mikeubell** [comment]
Is there a particular form that records this transition?

**Comment by sfdoran** [comment]
It's lame. All they need to do is rename the committee using the FPPC Form 410 and add "Officeholder" somewhere in the new name. 

What makes it really confusing is when they file their next 460, there is no distinction for transactions before and after the new name.

I'm thinking about OCRA amendments to deal with this issue - e.g. making them terminate the campaign committee first. Also a on my NetFile wishlist.

**Comment by mikeubell** [comment]
moved to backend-static
