### ISSUE TITLE
C3 directives

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#31]
Angular directives for the C3 visualizations. @ajmobidesign anything to add?

**Comment by bcipolli** [comment]
@adborden Any objection if we move this to the frontend repo?

**Comment by bcipolli** [comment]
no response = no objection :) Please see https://github.com/caciviclab/disclosure-frontend-alpha/issues/84

**Comment by adborden** [comment]
On Mon, 2016-01-25 at 10:29 -0800, Ben Cipollini notifications@github.com wrote:

> no response = no objection :) Please see https://github.com/caciviclab/disclosure-frontend-alpha/issues/84

:+1:

## 

Aaron Borden
Human and Hacker
