### ISSUE TITLE
Contributors guide

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#33]
A policy describing how we work on the project (both code and not code), which will help us work together remotely. This was discussed in the September 2015 meeting.

**Comment by adborden** [comment]
#36 addresses this.

**Comment by adborden** [comment]
@jnmarcus suggested this be moved to the wiki or http://caciviclab.org/

**Comment by adborden** [comment]
Pending [caciviclab.github.io #5](https://github.com/caciviclab/caciviclab.github.io/pull/5).

**Comment by bcipolli** [comment]
Beyond the above PR, it would be great to define a style guide. It isn't self-evident from the code how strictly PEP8 guidelines will be followed, whether camel_casing is important, etc.

If there are simple rules, they could be added to the README.md. If the current code is violating those rules, we should probably take care of it ASAP, as the code is gonna start churning soon :)

**Comment by tdooner** [comment]
Agreed, preferably automated checks. My team maintains a project which provides quick feedback via pre-commit git hooks: https://github.com/brigade/overcommit. Perhaps that could be added to the installation process to enforce style guidelines. But if we're just running flake8 or something, we probably don't need to bring in something that heavy (since it requires Ruby).

**Comment by bcipolli** [comment]
https://github.com/california-civic-data-coalition/django-calaccess-raw-data is using `pep8` and `flake8` in their `.travis.yml`. I am +1 to add those here.

Cool tool. I'm simple-simple (pep8/flake8), but good to know that if we want something more, there's a nice tool to make it happen!

**Comment by tdooner** [comment]
Yeah, a travis-ci run of flake8/pep8 seems like a good way to do this to me too.

**Comment by bcipolli** [comment]
OK, seems that opening a new issue to do that specifically (since it will take code changes to get the travis build to pass) is worthwhile. See #99.

**Comment by bcipolli** [comment]
Fixed in #181
