### ISSUE TITLE
Clean up the directory structure as per django convention

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#42]
@jnmarcus pointed out that the directory structure is a bit confusing. Here's what django would do:

```
$ django-admin startproject disclosure
$ cd disclosure
$ django-admin startapp ballot
```

Produces a directory structure like this:

```
disclosure
├── ballot
│   ├── admin.py
│   ├── __init__.py
│   ├── migrations
│   │   └── __init__.py
│   ├── models.py
│   ├── tests.py
│   └── views.py
├── disclosure
│   ├── __init__.py
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
└── manage.py
```

Legacy from django-calaccess-raw-data, we have a project name with a hyphen (invalid in python) and the main app is named "project" under `disclosure-backend/disclosure-backend/project`.

**Comment by bcipolli** [comment]
@adborden Can you assign this to me? Seems important to do while there's little development activity.

Once the project starts going, this is going to be challenging to change.

**Comment by tdooner** [comment]
This is a little better than it was as-of-writing, but still the `disclosure_backend/project/` directory could probably be dealt with. It'd be great to take care of this soon, I agree!

**Comment by bcipolli** [comment]
I believe this is done; closing.
