### ISSUE TITLE
Admin Candidate photo uploads aren't working

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#58]
Candidate photos are getting dumped in the current directory, not MEDIA_ROOT. Fetching the URL for 'em also doesn't work.

**Comment by bcipolli** [comment]
This should be taken care of soon, to facilitate front-end development.

**Comment by bcipolli** [comment]
Per documentation on good APIs, we should return URLs to candidate photos (when available).

Will punt this to 0.2; this didn't have to be done for the API...

**Comment by bcipolli** [comment]
Fixed in #187
