### ISSUE TITLE
Understand Netfile data and identify what transforms we need to serve the api

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#60]
You can see what we're working with. Having an understanding of CalFormat and campaign finance laws would be helpful.
https://drive.google.com/folderview?id=0BzfApHVcD3yDaFRGREs0Qjl2eWM&usp=sharing

**Comment by mikeubell** [comment]
Aaron,

Does NetFile have documentation on the data?  That is what is the provenance, time frame, etc.  I see they do not have a report_num field so we would have to know if this is only the most recent amendments or all amendments, etc.  I could load it up and look for duplicates, etc.

**Comment by adborden** [comment]
Very little documentation. They're using swagger spec for their api, so you get some information here https://netfile.com/Connect2/api/swagger-ui/#!/public

The CSVs linked above are created from `/public/campaign/export/cal201/transaction/year`. Forms/schedules are mapped to transaction types, available from `/public/campaign/list/transaction/types` and agencies are available `/public/campaign/agencies`

So for Oakland F460A, you're looking for COAK, agency id 13, transaction type 0. There are several amount fields, and I'm not sure if that includes amendments, or how to double check the numbers are accurate. That's about as far as I took it.

**Comment by adborden** [comment]
This is another piece of the puzzle, understanding the column names, which are very similar to other related data sources https://data.sfgov.org/City-Management-and-Ethics/Campaign-Finance-Data-Key/wygs-cc76

**Comment by mikeubell** [comment]
I've done a little poking at this data.  I created an SQL table and ran some queries.  My understanding is that tranactiontype=0 should be the A section of F460.  Running:
select sum(tran_amt1) from netfile where filerid = 'COAK-153682' and transactiontype='0'
where 'COAK-153682' is the Schaaf mayoral committiee gets 684098.90 which is too high, the Socrata data gives: 449721.11.
There are about 1100 records for Schaaf for which there are duplicates in trans_id, tran_amt1, tran_naml and tran_date.  Examining one pair they differ on the "filingid".  I guess that this may indicate an amended filing, but I don't see anything in the 96 columns of data here that would indicate that.

**Comment by bcipolli** [comment]
@andrell81 and I are working on some docs to help with this. @adborden , can you assign this to @andrell81 ?

**Comment by bcipolli** [comment]
I've assigned this to myself on behalf of @andrell81 (who is leading the effort to understand the netfile data) and myself (my [database schema proposal](https://github.com/caciviclab/caciviclab.github.io/wiki/Data-relationships---Database-schema) for transforming the data is the only one I've seen so far).

This issue is kind of gigantic. It involves: 
- Design a database schema
- Implement the schema
- implement code to transform data from the `netfile` schema to the database schema.

It would be great to break the issue into those parts, if others are cool with that.

**Comment by bcipolli** [comment]
Check that; this one is really about designing the database schema. Will open issues for the other two, if they don't already exist.

**Comment by adborden** [comment]
@bcipolli I can't assign @andrell81 until she accepts the invite to caciviclab.

**Comment by bcipolli** [comment]
According to the data headers, the ballot measures should be embedded in the data. Unfortunately, netfile sets them all to `null`.

Seems useful to engage netfile and ask them why they have these fields if they're always `null`, and what would have to happen to make them _actually_ appear.

**Comment by adborden** [comment]
@bcipolli have you confirmed for which `transactionType` this is true? We've been aware that those headers are unpopulated, but I've only looked at transactionType 0, which corresponds to the form 460A. I was hoping there would be another form which would give us a clue.

@bcipolli are you and @andrell81 the best folks to reach out to Netfile?

**Comment by bcipolli** [comment]
@adborden I will look deeper into it; I do see some sparse population of that field. Is there somewhere that lists the meaning of the different `transactionType`s?

We will chat with our city contact tonight about reaching out to Netfile; she's made offers to us on multiple occasions to facilitate that.

**Comment by adborden** [comment]
@bcipolli It's from the netfile API, link above. Here's a csv sample.

https://drive.google.com/open?id=0BzfApHVcD3yDWlhBbE1pOWdQakk

**Comment by bcipolli** [comment]
@andrell81 chatted yesterday about the current work and what needs to change. More needs to be done for other form data.

**Comment by bcipolli** [comment]
I'm going to close this item, as the main Form 460 data transformation is "done" (we have issues for entity resolution, but we are using the data well). Will open specific issues for other form data.
