### ISSUE TITLE
map mockup to api

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#61]
@jnmarcus @amandaric @sseiter review the existing  mockups and identify the specific data that is required for the api to consume.

i.e. mapping the mockups to the line items in the CalFormat Forms (or even to the column names from our [data dictionary](https://data.sfgov.org/City-Management-and-Ethics/Campaign-Finance-Data-Key/wygs-cc76))

**Comment by adborden** [comment]
@sseiter I believe this is on the agenda for our next meeting?

**Comment by bcipolli** [comment]
A first pass, mapping the mock-ups to a database schema and API endpoints, can be found here. Comments welcome!

@jnmarcus What's missing is the specific XML elements for each API endpoint. Could you create a doc/spec for that somewhere, and ping me to help flesh it out? I know some of this has been done by @adborden, but I'm not clear which endpoints have been mocked up and which have not.

**Comment by bcipolli** [comment]
This was fixed in #177
