### ISSUE TITLE
Cal-Access import segfaults before finishing

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend#66]
AFAICT, the RCPT_CD table is where the Form 460 Schedule A data lives. It is what currently powers the meager API we support.

However, there is currently no data there! This seems fishy....

Perhaps related to some data import bugs we didn't fix during the transition from calaccess_raw to being a dependency?

**Comment by tdooner** [comment]
The output of the cron log ends abruptly:

```
Loading data files
 Loading CvrSoCd
 Loading Cvr2SoCd
 Loading CvrCampaignDisclosureCd
  Table record count doesn't match CSV. Table: 337080   CSV: 337081
 Loading Cvr2CampaignDisclosureCd
  Table

Stderr (if any):
```

**Comment by tdooner** [comment]
The plot thickens:

```
tom@opencal:~$ sudo cat /var/log/kern.log
Oct 12 00:42:38 opencal kernel: [2338667.664301] python[2244]: segfault at 24 ip 0000000000506db5 sp 00007fff95f068f0 error 6 in python[400000+2bd000]
Oct 12 00:42:38 opencal kernel: [2338667.672856] Core dump to |/usr/share/apport/apport 2244 11 0 2244 pipe failed
Oct 13 00:41:53 opencal kernel: [2425022.241417] python[3326]: segfault at 24 ip 0000000000506db5 sp 00007fff0f4c9d50 error 6 in python[400000+2bd000]
Oct 14 00:41:51 opencal kernel: [2511420.977258] python[26956]: segfault at 24 ip 0000000000506db5 sp 00007fffc898eb20 error 6 in python[400000+2bd000]
Oct 15 00:41:47 opencal kernel: [2597816.823741] python[29560]: segfault at 24 ip 0000000000506db5 sp 00007fff2a2ec7c0 error 6 in python[400000+2bd000]
```

Suspicious... every day, 33 minutes after the cronjob starts.

**Comment by adborden** [comment]
Is this still an issue? I think we made some changes upstream to load in batches.

**Comment by bcipolli** [comment]
Change was accepted upstream, `requirements.txt` updated in https://github.com/caciviclab/disclosure-backend/commit/c430a924e01561a08386983f0dc036a69dcefc3a#diff-b4ef698db8ca845e5845c4618278f29a
