### ISSUE TITLE
Election API endpoint

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#7]
Returns an election entity `/agency/:id/election/:date` and looks [something like this](https://drive.google.com/open?id=0B2fKtH2QvtcocE1kX0hKYi1SWTQ).

**Comment by adborden** [comment]
```
/* 
    API endpoint:
    /agency/:id/election/:date
*/

{
    "agency_id": 1,                                 // int
    "agency_name": "agency_name",                   // string
    "election": "date",                             // string
    "by_source": {
        "candidate": 100.0,                         // float
        "self_funded": 100.0,                       // float
        "independent_expenditures": 100.0           // float
    },
    "by_geography": {
        "local": 100.0,                             // float
        "in_state": 100.0,                          // float
        "out_state": 100.0                          // float
    },
    "races": [
        {
            "race_id": 1,                           // int
            "race_type": "type of race",            // string, optional, e.g: "City Council"
            "race_name": "race_name"                // string, e.g: "District 1"
        }
    ]
}
```

**Comment by adborden** [comment]
cc @seanius @erispoe

**Comment by adborden** [comment]
This endpoint was requested by the folks working on some dataviz prototypes, so the there might be some flux in these.

**Comment by seanius** [comment]
In adc9794d I added a zipcode_metro model, which we can use for mapping zipcodes to metro (and state) names.  this can be used for determining the "in_state" type information.

**Comment by seanius** [comment]
Most up to date version is here:

https://github.com/opencalifornia/ux/blob/master/api-specs/election.json

**Comment by seanius** [comment]
running commentary on our understanding semantics of these fields etc:

this is for contribution data (schedule 460A)
    "agency_id":  netfile agency (should be modelled by NetfileAgency)
    "agency_name":  same
    "election": we'll need some kind of election date registry
    "by_source": {  <---  total campaign contributions by source, it's not entirely clear what deliniation is actually wanted here.   individual (with a sub-division of candidate vs other individual) vs organization (with a sub-division of public-funding vs other organizations).  Let's clear up with UI folks before setting this in stone to make sure we're on the same page.
        "candidate":  
        "self_funded":
        "independent_expenditures":
    },
    "by_geography": { <- i think we understand this one a bit better.
        "local":  <- contributions coming from the same city
        "in_state":  <- think they mean "in_metro"?  contributions from the same metro area (see zipcode_metro)
        "out_state": <- likewise, inverse of above.
    },
    "races": [ <- we don't have anything for this right now... maybe we have to semi-manually maintain this?  this is the list of individual races on the ballot for a particular election
        {
            "race_id": <- arbitrary but consistant id
            "race_type":  <- string, optional, e.g: "City Council"
            "race_name": <- string, e.g: "District 1"
        }
    ]

**Comment by adborden** [comment]
Anyone know where this data is supposed to come from?

**Comment by mikeubell** [comment]
Netfile has an agency_id but callaccess does not.  Do we want to recreate one for callaccess or drop it and just use agency_name as this aught to be unique.

**Comment by mikeubell** [comment]
What is the difference between "candidate" and "self_funded"?

**Comment by adborden** [comment]
@bcipolli as written, I don't think this is correct. I think we should re-write this story. I think it mostly corresponds to the `/ballot/:locality_id` endpoint from [the wiki](https://github.com/caciviclab/caciviclab.github.io/wiki/Data-relationships---Database-schema#feeds-1).

**Comment by bcipolli** [comment]
See #6 for relevant API endpoints.
