### ISSUE TITLE
Netfile partial downloads

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#81]
As a developer, I want Netfile django commands to figure out what to download based on what's already in the database, so that downloads/loading is much much faster.

Maybe have a switch to allow for a full download.

**Comment by ebrensi** [comment]
yes probably the 2014 data is not going to change much, if at all.  There is no point in re-downloading it every night.  

Just to clarify, this is a request for someone to implement incremental updates for netfile data.   The relevant files to look at are
 [`/netfile/connect2_api.py`](https://github.com/caciviclab/disclosure-backend/blob/master/netfile/connect2_api.py) 
and 
[`/netfile/management/commands/downloadnetfilerawdata.py`](https://github.com/caciviclab/disclosure-backend/blob/master/netfile/management/commands/downloadnetfilerawdata.py)

**Comment by bcipolli** [comment]
The API to browse is:
https://netfile.com/Connect2/api/swagger-ui/

The most generic query form I see is:
https://netfile.com/Connect2/api/swagger-ui/#!/public/Query

According to what I've seen, there are specific filing deadlines for each relevant form type. So it shouldn't be necessary to scrape and re-scrape data.

The only potential caveat that comes to mind: do we need to be concerned about data being changed/corrected at a later date? Worth investigating.

**Comment by bcipolli** [comment]
How about this for a design:
- Data for past years are downloaded in full, and cached as CSV files. If those CSV files exist, the download is skipped.
- Data for current years are downloaded incrementally, a la https://github.com/caciviclab/disclosure-backend/issues/125

Alternately, we could make all downloads incremental, a la https://github.com/caciviclab/disclosure-backend/issues/125.

**Comment by bcipolli** [comment]
I am happy with the current ability of the commands to handle this, so will close.
