### ISSUE TITLE
Add party affiliation to candidate model

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#88]
Candidate model needs a field for the candidate's political party.

**Comment by mikeubell** [comment]
Now I am confused... having procrastinated long enough there no longer seems to be a candidate model. The BallotItemResponse claims to be for a referendum or candidate, but I don't see any fields that are useful for a candidate.

**Comment by mikeubell** [comment]
Ok, I guess the candidate has moved to office_election/models.py and the Party field has been added. I am guessing the comment in BallotItemResponse that says it can be a candidate is wrong.
I will close this issue.
