### ISSUE TITLE
the nefile BAL_JURIS needs entity resolution

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/disclosure-backend#89]
There does not appear to be a standard for how to fill this field:
select distinct BAL_JURIS from netfile_cal201_transaction where BAL_JURIS like '%akland%';
BAL_JURIS  
  City of Oakland, CA  
  City of Oakland  
  Oakland, CA  
  Oakland

**Comment by bcipolli** [comment]
@mikeubell Can you check if `Juris_Cd` is the same for those rows?

**Comment by mikeubell** [comment]
Yes it is the same.  It is empty.

**Comment by bcipolli** [comment]
:sob: thanks!

**Comment by bcipolli** [comment]
@mikeubell Do we need this field for anything? We pass the city `shortcut` in to the script, and we can resolve that to the city name...

**Comment by mikeubell** [comment]
How do we tell what records are for which city?

**Comment by bcipolli** [comment]
We have a list of cities from netfile to download. Then we get data from each city individually. So we know the city for each row already, when we download each csv file. So I think this information is duplicate.

**Comment by mikeubell** [comment]
Given that, I agree that it is redundant.

**Comment by bcipolli** [comment]
Great, that makes life easy :D Closing!
