### ISSUE TITLE
Load Netfile data into DB

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend#9]
I'm assuming we should follow CCDC's pattern of download, clean, transform, load. We currently are downloading a fixed range of records to CSVs. Create some basic models (or single model) that closely aligns with the Netfile schema. Any transforms we do on top of that should probably be stored/treated separately.

**Comment by seanius** [comment]
the zipcode_metro app could serve as a template for how to create a django model.  it re-uses a lot of the existing calaccess_raw guts, though doesn't do any cleaning on the data it downloads.

**Comment by adborden** [comment]
I"m going to call this done, since we have the [infrastructure for it](http://disclosure.caciviclab.org/admin/netfile/) and it's loading. There's still some question of what are we going to transform it to, but that will land in another issue.
