### ISSUE TITLE
Make codebase PEP8 / flake8 compatible

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-backend#99]
In #33 we discussed adding PEP8 / flake8 compatibility to a "contributing" doc. To enforce that, we should:
- Add pep8/flake8 to `.travis.yml`
- Make code changes to the existing codebase so that pep8 and flake8 pass.

**Comment by bcipolli** [comment]
Fixed in https://github.com/caciviclab/disclosure-backend/pull/101 , just waiting for review.

**Comment by tdooner** [comment]
:+1: looks done to me.
